### ISSUE TITLE
error: unable to recognize "/des/eis/ipes/templates/pks/weblogic-build/weblogic-domain/weblogic-domains/domain8/domain.yaml": no matches for kind "Domain" in version "weblogic.oracle/v3"

### ISSUE THREAD

**Issue by madhuchilipi** [oracle/weblogic-kubernetes-operator#1135]
Hi Team,

I am trying to create the domain using weblogic operator 2.0 i am facing API issue. Could you please help.

$ kubectl apply -f $CI_PROJECT_DIR/weblogic-domain/weblogic-domains/domain8/domain.yaml -n pks-cicd
error: unable to recognize "/des/eis/ipes/templates/pks/weblogic-build/weblogic-domain/weblogic-domains/domain8/domain.yaml": no matches for kind "Domain" in version "weblogic.oracle/v3"

Regards,
Madhu

**Comment by rjeberhard** [comment]
Sorry for the slow response!  Last Thursday was a holiday in the U.S. and almost everyone took Friday as well.  The error suggests that you don't yet have the custom resource definition (CRD) for the Domain type.  The operator should install this CRD in your Kubernetes cluster.  Can you share the output of `kubectl describe crd domains.weblogic.oracle`?  If this command returns that there is no such CRD, then I'd be interested to know if the operator installed successfully.

**Comment by charuni2018** [comment]
seems CRD is running, can you suggest further.

**Comment by lennyphan** [comment]
[crdoutput_txt.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/3402891/crdoutput_txt.txt)

Attaching the CustomResourceDefinition from the command ```kubectl describe crd domains.weblogic.oracle```

**Comment by lennyphan** [comment]
The version of the Domain that your domain.yaml represents is version "weblogic.oracle/v3" but the Domain described by your CRD that is deployed is 'Version: v2'.  Hence the error that the deployment of the Domain is not recognized since it is v3.  The best thing to do is:

1. delete the deployed CRD
2. Undeploy and redeploy the Operator (using helm) from the same cloned repository that your generated domain.yaml is created from.  This way the versions of the CRD deployed by the Operator and the domain.yaml you're using match.

**Comment by lennyphan** [comment]
Operator was updated to version 2.2.1.
CRD was deleted
Operator was redeployed to the k8s cluster

The install of the updated Operator deployed the latest CRD at v4 which resolved the issue.
