### ISSUE TITLE
Modify the configuredManagedServerCount/ dynamic cluster size during runtime

### ISSUE THREAD

**Issue by wenjian80** [oracle/weblogic-kubernetes-operator#1167]
Is there a way to modify the configuredManagedServerCount/dynamic cluster size during run time for domain in an image?

Imagine let say we have been running the default max size dynamic size of 5 for some time and we need to do scale the number of pods/ms to cater for the load beyond that.

Do we have the edit the max dynamic cluster via the admin console or there is a configuration in the yaml for that?

**Comment by tbarnes-us** [comment]
It is possible to make runtime changes for specific configuration attributes that _do not_ affect topology in a way that doesn't require a restart - see https://github.com/oracle/weblogic-kubernetes-operator/issues/1139. But modifying the dynamic cluster size or adding new servers is not one of these attributes. 

Instead, it's best to pre-configure your cluster so that its sized a little larger than the maximum size you plan to expand it to (and of course to rigorously test at this maximum size to make sure that your system can scale as expected). If instead you need to change the configuration, then it's necessary to restart the entire domain once you make the change so that the Operator reruns the 'introspector job' and detects the new maximum cluster size.

**Comment by tbarnes-us** [comment]
One of the reasons for this limitation is that the current Operator learns the cluster topology using the 'introspector job' which it only runs before a domain starts its first WL pod.

**Comment by wenjian80** [comment]
Understood, thanks
