### ISSUE TITLE
prepare.sh will not run on Ubuntu due to use of function keyword

### ISSUE THREAD

**Issue by amyles** [oracle/weblogic-kubernetes-operator#1251]
The [prepare.sh](https://github.com/oracle/weblogic-kubernetes-operator/blob/master/kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/prepare.sh) script will not run on Ubuntu due to the use of the function keyword, this results in files not being copied into container. 
Changing this section:
```
function usage {
  echo usage: ${script} -i file [-h]
  echo "  -i Directory, must be specified."
  echo "  -h Help"
  exit $1
}
```
to 
```
usage() {
  echo usage: ${script} -i file [-h]
  echo "  -i Directory, must be specified."
  echo "  -h Help"
  exit $1
}
```
means it's more POSIX compliant and runs on Ubuntu,

**Comment by tbarnes-us** [comment]
I know this is an old Issue, but I'm not sure if it should be pursued.  

I'm assigning this to Monica and Ryan for triage.  

Note: if we do pursue this, I recommend adding a compile/unit-test step that verifies that all scripts are 'ubuntu compliant'.

@amyles : Assuming ubuntu support becomes a priority, do you know if there some kind of global shell flag that can be used to make ubuntu more forgiving? (Instead of removing use of the relatively intuitive 'function' keyword.)

**Comment by robertpatrick** [comment]
@tbarnes-us @mriccell @rjeberhard I see no reason to delay changing the function declaration syntax.  There is zero advantage of using this bash-specific syntax when even BASH sites say that the other syntax is preferred.

**Comment by tbarnes-us** [comment]
@robertpatrick I've filed internal tracking JIRA OWLS-94874 to track the issue. Note that `grep` reveals several hundred occurrences.
