### ISSUE TITLE
/usr/bin/env: ‘bash\r’: No such file or directory in sh scripts

### ISSUE THREAD

**Issue by muhammadwasay** [oracle/weblogic-kubernetes-operator#1447]
While following the quick start guide at
https://oracle.github.io/weblogic-kubernetes-operator/quickstart/ 
I faced the following errors when running bash script files.
/usr/bin/env: ‘bash\r’: No such file or directory in sh scripts
I am running ubuntu 18.0.4 os and i faced this issue in the folloing files
- weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain-credentials/create-weblogic-credentials.sh
- weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain.sh

I fixed this issue by following the below steps as suggest by following stackoverflow post.
sed $'s/\r$//' ./create-weblogic-credentials.sh > ./create-weblogic-credentials-unix.sh
https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory

The bash scripts files should be fixed.

Update:
There are others files also that contain the same issue. I guess these file were commited from a windows machine and the line ending were effected.

**Comment by marinakog** [comment]
Hi @muhammadwasay  it looks like it fixed already, please confirm if you still see same issue

**Comment by Denesh11** [comment]
> Hi @muhammadwasay it looks like it fixed already, please confirm if you still see same issue

Please help me I was facing this same error while setup the flutter in lower compatible version

**Comment by tbarnes-us** [comment]
I'm assuming the issue was resolved long ago, but feel free to re-open if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

**Comment by azaylamba** [comment]
I am getting "/usr/bin/env: ‘bash’: No such file or directory" when using Github desktop and trying to initial commit

**Comment by tbarnes-us** [comment]
This issue is closed.

For questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue. For general background about contributing to the WKO project, see https://oracle.github.io/weblogic-kubernetes-operator/developerguide/
