### ISSUE TITLE
Installing the operator fails with javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by kocic11** [oracle/weblogic-kubernetes-operator#1504]
When following the Quick Start guide the install command fails with an error:
helm install kubernetes/charts/weblogic-operator \
  --name sample-weblogic-operator \
  --namespace sample-weblogic-operator-ns \
  --set image=oracle/weblogic-kubernetes-operator:2.5.0 \
  --set serviceAccount=sample-weblogic-operator-sa \
  --set "domainNamespaces={}" \
  --wait
The pod logs show the following error (see the attached log file):
io.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request
[error.log](https://github.com/oracle/weblogic-kubernetes-operator/files/4390293/error.log)

Please advise.

**Comment by rjeberhard** [comment]
We don't yet support Kubernetes 1.16 or above.

This is the bug against the JDK: https://bugs.openjdk.java.net/browse/JDK-8236039.

It's fixed in the upcoming maintenance release, JDK 11.0.7, which is planned to be available on April 14th.  As soon as that is available, we'll release a version of the operator based on that JDK.

**Comment by kocic11** [comment]
Thanks.
