### ISSUE TITLE
The value of USER_MEM_ARGS in domain-template.yaml is not configurable through an inputs yaml file

### ISSUE THREAD

**Issue by rishiagarwal-oracle** [oracle/weblogic-kubernetes-operator#1901]
The value of USER_MEM_ARGS in domain-template.yaml is not configurable through an inputs yaml file.

The value is hardcoded as: "-Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx512m " in domain-template.yaml 
Also the value is hardcoded as : "-Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx1024m " in jrf-domain-template.yaml

Like any other key in the template files, the value of USER_MEM_ARGS should also be overridable through an inputs.yaml file 

Right now the only option is to generate the domain.yaml file and then modify it to update the value

**Comment by rishiagarwal-oracle** [comment]
@rjeberhard @ankedia filed this issue as per our discussion

**Comment by tbarnes-us** [comment]
@rishiagarwal-oracle Is a resolution needed here? I ask because:

(1) I see there is a 'javaOptions' parameter in inputs. Is that sufficient for sample purposes? Anyone that needs to update the sample for their own uses can follow the pattern of the javaOptions parm to add more env var parms...
(2) The 'inputs' file and its attendant helper scripts are intended only for sample use, not production use.
(3) The domain resource YAML that the 'input' file generates can be modified directly -- just as many other modifications are typically needed when extending beyond a sample use case (thus requiring abandoning the inputs file approach).

Please feel free to re-open the Issue or start a slack conversation if you disagree.
