### ISSUE TITLE
Adminserver pod fails to start up if dataHome is set in domain CR and OKE cluster node pool is scaled up/down

### ISSUE THREAD

**Issue by watsh-rajneesh** [oracle/weblogic-kubernetes-operator#1970]
After scaling up (changing shape) for the OKE cluster node pool we are seeing the below error during startup of admin server pod.

```<Oct 5, 2020 7:55:55,733 PM GMT> <Emergency> <Store> <BEA-280060> <The store "_WLS_wrrcu1-adminserver" encountered a fatal error, and it must be shut down: weblogic.store.PersistentStoreFatalException: [Store:280105]The persistent file store "_WLS_wrrcu1-adminserver" cannot open file _WLS_WRRCU1-ADMINSERVER000000.DAT.
weblogic.store.PersistentStoreFatalException: [Store:280105]The persistent file store "_WLS_wrrcu1-adminserver" cannot open file _WLS_WRRCU1-ADMINSERVER000000.DAT.
	at weblogic.store.internal.PersistentStoreImpl.open(PersistentStoreImpl.java:571)
	at weblogic.store.admin.AdminHandler.activate(AdminHandler.java:159)
	at weblogic.store.admin.FileAdminHandler.activate(FileAdminHandler.java:230)
	at weblogic.store.admin.DefaultStoreService.start(DefaultStoreService.java:103)
	at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
	Truncated. see log file for complete stacktrace
Caused By: java.io.IOException: Error from fcntl() for file locking, Resource temporarily unavailable, errno=11
	at weblogic.store.io.file.direct.DirectIONative.openConsiderLock(Native Method)
	at weblogic.store.io.file.direct.DirectIONativeImpl$1OpenConsiderLockCallable.call(DirectIONativeImpl.java:41)
	at weblogic.store.io.file.direct.DirectIONativeImpl$1OpenConsiderLockCallable.call(DirectIONativeImpl.java:39)
	at weblogic.store.common.StoreRCMUtils.accountAsGlobal(StoreRCMUtils.java:91)
	at weblogic.store.io.file.direct.DirectIONativeImpl.openConsiderLock(DirectIONativeImpl.java:46)
	Truncated. see log file for complete stacktrace
> 
```

The file _WLS_WRRCU1-ADMINSERVER000000.DAT is on the shared NFS filesystem under /u01/shared/data/store/wrrcu1domain directory. 

In domain.yaml we set the dataHome for the domain as:

```
spec:
   dataHome: /u01/shared/data/store
...
```

A workaround we have currently is:

1. Edit domain.yaml and comment out dataHome setting.
2. Perform scale up/down of node pool
3. WLS pods come up fine without the above mentioned error.
4. Edit the domain. yaml and add back the dataHome setting
5. Pods are restarted automatically and come up fine without above error.

So Its only when the node pool is being scaled up while the dataHome setting is present in the domain CR that we hit this issue.

WebLogic Operator version: 3.0.0
WebLogic Version: 12.2.1.4
Using domain home in image.

**Comment by mriccell** [comment]
A workaround to this problem if the stores are placed in the Database.

**Comment by tbarnes-us** [comment]
Hi @watsh-rajneesh, I'm closing this issue.  There have been related ongoing discussions in slack IIRC, and I suspect you've already been participating.  Please feel free to re-open the Issue if you feel it's necessary, or simply continue the discussions in slack.

To summarize:

- Make sure all WL server pods are given a chance to shutdown gracefully before deleting a node. Otherwise k8s simply kills the entire VM without shutting it down normally, and this in turn looks like the Operating System itself abruptly crashed as far as NFS is concerned, which in turn leaves behind 'abandoned locks'. I think OKE now does the graceful shutdown.
- In the event of an uncontrolled "crash" (which should be relatively infrequent given the OKE graceful shutdown fix ^^^), you can recover by manually unlocking files:  copy them and then move the file copies back to their original location.
- With many caveats and great care, you can consider disabling locking. 
- The best option in my opinion is to move to NFS v4, because v4 has been around for almost twenty years and it handles abandoned locks far better than NFS v3.  OKE does not currently have v4 support, but it now appears to be on its roadmap by popular demand. Feel free to contact OKE PM directly if you haven't already (in order to add your imprimatur to NFS v4 enhancement request).

@rjeberhard FYI
