### ISSUE TITLE
Readiness probe issue if deployment failed to start

### ISSUE THREAD

**Issue by csegedicsaba** [oracle/weblogic-kubernetes-operator#2069]
We use readiness probe with ReadyApp as mentioned in #1395.
If our deployment failed to start the ReadyApp framework bypass the deployment and the pod became ready.

It would be great to use custom readiness probe or ability to use StartupProbe for this issue.
Or is there any solution to handle this case?

**Comment by anpanigr** [comment]
A successful application deployment is the minimum requirement for the ReadyApp framework to work.  As of now there is no plugin for custom readiness probe in WebLogic Kubernates Operator.

**Comment by tbarnes-us** [comment]
I'm assuming this issue was resolved as per the @rjeberhard note in Issue #1395 . Please feel free to re-open if I'm incorrect.

For future questions of this nature please feel free to use WKO's public `#operator` slack channel at `oracle-weblogic.slack.com` (sign-up here: `https://weblogic-slack-inviter.herokuapp.com/`). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.
