### ISSUE TITLE
domain.yaml generated by create-domain.sh has a duplicated serverService tag. 

### ISSUE THREAD

**Issue by wenjian80** [oracle/weblogic-kubernetes-operator#2076]
Any reason why i am hitting the below error? The domain yaml was generated by create-domain.sh under weblogic-kubernetes-operator/kubernetes/samples/scripts/create-soa-domain/domain-home-on-pv.Am using operator 3.0.1.

root@soak8master soainfra]# kubectl apply -f domain.yaml
error: error validating "domain.yaml": error validating data: [ValidationError(Domain.spec.clusters[0].serverService): unknown field "affinity" in oracle.weblogic.v8.Domain.spec.clusters.serverService, ValidationError(Domain.spec.clusters[1].serverService): unknown field "affinity" in oracle.weblogic.v8.Domain.spec.clusters.serverService, ValidationError(Domain.spec.serverPod): unknown field "serverService" in oracle.weblogic.v8.Domain.spec.serverPod]; if you choose to ignore these errors, turn validation off with --validate=false
[root@soak8master soainfra]# kubectl apply -f domain.yaml  --validate=false
The Domain "soainfra" is invalid: spec.clusters.serverPod: Invalid value: "null": spec.clusters.serverPod in body must be of type object: "null"

The domain.yaml generated has a duplicated serverService tag. 
[domain.yaml.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/5605759/domain.yaml.txt)

**Comment by tbarnes-us** [comment]
I'm sorry there was no response directly in the Issue, this one somehow flew under the radar.

I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

@rjeberhard FYI
