### ISSUE TITLE
the Administration Server and Managed Servers didn't start

### ISSUE THREAD

**Issue by SKerry1216** [oracle/weblogic-kubernetes-operator#3470]
After I run the create-domain.sh to start the create on-pvc job,the job completed well.But the Administration Server and Managed Servers didn't start.
![QQ截图20220929150929](https://user-images.githubusercontent.com/59678918/192963659-bf76937f-de20-438c-9993-8d169d2bfb52.png)
here is the input file
![QQ截图20220929151126](https://user-images.githubusercontent.com/59678918/192964019-20788fcd-6b3b-4842-a7d5-d34e539e8849.png)
Any advices can help me to find the problem.
Thanks！

**Comment by tbarnes-us** [comment]
Sorry for the late response.

Please consult the [Domain Debugging ](https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/model-in-image/debugging/) guide, this troubleshooting guide is in the Model in Image documentation but largely applies to all domain home source types. Also, if you're on OpenShift, check for its specific additional instructions in the doc.

And if this is still an issue after the above, then please start a discussion on Slack if that's an option as that'll make it easier to circle in various experts as needed. Instructions are [here](https://oracle.github.io/weblogic-kubernetes-operator/userguide/introduction/get-help/). If Slack isn't an option, then please post the Kubernetes provider that you're using, your domain's 'get -o yaml', the job pod's 'get -o yaml' and 'logs', the 'get -o yaml' for the PV and PVC, and any error/warning events in the domain's namespace. Events are usually automatically cleaned up over time, so rerunning the example may be necessary to get at them.

**Comment by tbarnes-us** [comment]
No. The 'domainPVMountPath' is the logical root directory of the PV within pod itself, which, by convention, is set to '/shared'. The '/scratch/k8s_dir' directory is the host path directory that the PV is using to store its files from '/shared'.  IIRC, the most common problem with domain on PV host paths is permissions. For sample purposes, 'chmod 777 /scratch/k8s_dir' (but I suspect the instructions or scripts already do something similar?).

If that doesn't help:

Instead of using this issue for continued discussions, please switch to Slack if that's an option. That'll make it easier to circle in various experts as needed, and it also tends to get faster responses.  Instructions are [here](https://oracle.github.io/weblogic-kubernetes-operator/userguide/introduction/get-help/).
