### ISSUE TITLE
WLS operator

### ISSUE THREAD

**Issue by yannalf** [oracle/weblogic-kubernetes-operator#4007]
Is it supported on EKS ? Installation works but looks like the ingress with traefik do not

**Comment by sankarpn** [comment]
@mriccell Do we support WKO on EKS?

**Comment by mriccell** [comment]
The operator supports running on production-quality Kubernetes environments, including on-premises, cloud offerings where Kubernetes is supplied for you, and cloud offerings where you set up Kubernetes yourself. Please refer to the support statement [Doc ID 2790123.1](https://support.oracle.com/epmos/faces/DocContentDisplay?id=2790123.1). https://oracle.github.io/weblogic-kubernetes-operator/introduction/platforms/environments/.  EKS is a production-quality Kubernetes environment so we do support the Operator and WebLogic running on EKS but we have not certified.  We do have customers running on EKS with the Operator in production.
You might want to use the AWS Ingress controller instead of Traefik see https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html
