### ISSUE TITLE
Admin Server Does not Have Cluster IP

### ISSUE THREAD

**Issue by jkramplify** [oracle/weblogic-kubernetes-operator#4039]
Why is admin server not having cluster ip address? We want to expose admin server but we don't want to use nodePort. Rather we want to expose it using an ingress. However we can't use ingress cause the admin server service does not have a cluster ip address. So how to make it have a cluster ip address so we can use ingress to expose the admin server?

Edit:
weblogc-kubernetes-operator version: 4.0.0

**Comment by rjeberhard** [comment]
Hi, @jkramplify... I'm not understanding. The operator creates ClusterIP services for each server instance, including for the admin server. There is an option to additionally create a NodePort service for the admin server, but the ClusterIP service still exists. Can you list the services in your namespace?

**Comment by jkramplify** [comment]
Hi @rjeberhard 

ClusterIp Service is indeed created however, it has no IP assigned.

```
service/domain-admin-server      ClusterIP   None          <none>        7001/TCP   2d19h
service/domain-cluster           ClusterIP   11.2.64.56    <none>        8001/TCP   5d23h
service/domain-m1                ClusterIP   None          <none>        8001/TCP   5d23h
```

**Comment by rjeberhard** [comment]
Yes, that's true. I think of these services as ClusterIP services because they are not NodePool services. They are actually headless services (https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) because they don't need an independent IP address as they have a one-to-one relationship with a specific pod.
