### ISSUE TITLE
Allow starting zero managed servers

### ISSUE THREAD

**Issue by markxnelson** [oracle/weblogic-kubernetes-operator#60]
Ryan knows what to do :)

from Grzegorz

**Comment by vanajamukkara** [comment]
The other option to have zero managed servers is by changing replicas in clusterStarup in domain-custom-resource.yaml. 
But after changing the replicas to 0 for a cluster in clusterStartup in domain-custom-resource.yaml, it still leaves one managed server pod running instead of bringing down all the managed servers.
