### ISSUE TITLE
weblogic-operator container starts with errors about /operator folder permission until it stops due to  SIGTERM to java process  11

### ISSUE THREAD

**Issue by denismaggior8** [oracle/weblogic-kubernetes-operator#880]
Using Minishift, when starting up weblogic-operator container complains about /operator folder permission.
Multiple errors about "Could not create Operator Liveness file /operator/.alive" are logged too, until OpenShift terminate the container.

```
mkdir: cannot create directory '/operator/internal-identity': Permission denied
sed: couldn't open temporary file /operator/sedDS6zjk: Permission denied
...

2019T15:24:15.172+0000","thread":17,"fiber":"","level":"INFO","class":"oracle.kubernetes.operator.OperatorLiveness","method":"run","timeInMillis":1549725855172,"message":"Could not create Operator Liveness file /operator/.alive","exception":"","code":"","headers":{},"body":""}

{"timestamp":"02-09-2019T15:24:20.174+0000","thread":17,"fiber":"","level":"INFO","class":"oracle.kubernetes.operator.OperatorLiveness","method":"run","timeInMillis":1549725860174,"message":"Could not create Operator Liveness file /operator/.alive","exception":"","code":"","headers":{},"body":""}
Sending SIGTERM to java process  11
```

**Comment by denismaggior8** [comment]
```
$ minishift version
minishift v1.30.0+186b034

$ minishift ssh docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      07f3374/1.13.1
 Built:           Fri Dec  7 16:13:51 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      07f3374/1.13.1
 Built:           Fri Dec  7 16:13:51 2018
 OS/Arch:         linux/amd64
 Experimental:    false

```

**Comment by markxnelson** [comment]
Hi @denismaggior8 we don't strictly support minishift, but we have been working to certify and support openshift.  I suspect you are hitting an issue I saw during that work.  OpenShift by default applies a security context and runs the container with a different userid, like 800001000, instead of 1000 (oracle), and so it probably does not have permission to access that directory.  I had to apply the anyuid SCC to the container to get it to run right.

**Comment by markxnelson** [comment]
for example, see https://weblogic.cafe/posts/weblogic-on-openshift/ and search for anyuid

**Comment by markxnelson** [comment]
and this: https://blog.openshift.com/understanding-service-accounts-sccs/

**Comment by denismaggior8** [comment]
I think you are right, look what I can see if I enter within the weblogic-operator container:

```
sh-4.2$ id -a
uid=1000180000 gid=0(root) groups=0(root),1000180000
sh-4.2$ touch /operator/denis
touch: cannot touch '/operator/denis': Permission denied
sh-4.2$ whoami
whoami: cannot find name for user ID 1000180000
```

I will double check the link you posted and try to solve the issue (may be the same I encountered with the Logstash container).

Also, I know that you do not official support Minishift but I think it's useful for demo or training purpose to have Weblogic and the operator working also on this environment. I'm in the process of following  your tutorial and modifying it to let Weblogic/Operator run on Minishift as well, I'll be back to you sharing the result of my research activities (may be with a pull request for the README.md file I'm writing).

Cheers

**Comment by markxnelson** [comment]
great, thanks @denismaggior8 - we do try to help anyway even though it is not officially supported, when we can!

**Comment by maidirepelle** [comment]
@denismaggior8 @markxnelson I've tried and I think I've found a WA to solve the issue.

Please look at this and see if could work for you:

Substitute ${{PROJECT_EXP}} with your namespace.
```
oc create sa weblogicsa -n ${{PROJECT_EXP}}
oc adm policy add-scc-to-user anyuid -z weblogicsa -n ${{PROJECT_EXP}}
```

After creating the custom service account, you'll add the service account instead of the 'default' one in the my-operator-values.yaml file.

Re-do all the steps of launching the operator after a `helm del --purge weblogic-operator` command.
Now the operator is run as 'root' user and does not report the issue just reported.

**Comment by josequaresma** [comment]
That worked for me @maidirepelle , thanks! It does required admin rights to the cluster though.

In case one wants to use the default service account, the following command can be executed instead:
`oc adm policy add-scc-to-user anyuid -z default -n`
